root: true
env:
  browser: true
  es6: true
  node: true
parserOptions:
  parser: babel-eslint
extends:
  - airbnb-base
  - plugin:vue/recommended
plugins:
  - vue
rules:
  no-console: 'off'
  vue/no-v-html: 0
  max-len:
    - error
    - 200
settings:
  import/resolver:
    nuxt:
      extensions:
        - '.js'
        - '.vue'
